server:
  port: 12346
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///oauth2?serverTimezone=UTC
    username: root
    password: allong
mybatis:
  type-aliases-package: com.example.springsecurityjwt.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.springsecurityjwt.mapper: DEBUG
