server:
  port: 10010
spring:
  datasource:
    url: jdbc:mysql:///mybatis_plus?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: allong
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/mybatis/*.xml
logging:
  level:
    com.example.mybatisplus1: debug
