server:
  port: 9009
spring:
  datasource:
    url: jdbc:mysql:///oauth2?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: allong
  main:
    allow-bean-definition-overriding: true #允许Bean 覆盖
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yj.oauth2.domain
logging:
  level:
    com.yj.oauth2: debug
#mybatis