server:
  port: 9009
spring:
  datasource:
    url: jdbc:mysql:///spring_security?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: allong
mybatis:
  type-aliases-package: com.yj.springsecuritydemo.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.yj.springsecuritydemo: debug
