server:
  port: 12345

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///oauth2?serverTimezone=UTC
    username: root
    password: allong
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.springsecurity.domain

